### PR TITLE
Returning reply not available when no nodes available

### LINKED ISSUE #74: double callback and connection timeouts
after merging #70 and #72, we are now getting timeouts and double callbacks on connections.

```
$ make test
NODE_PATH=lib/ node_modules/whiskey/bin/whiskey --real-time --scope-leaks --tests "test/cql2.js test/cql3.js test/thriftHostPool.js test/thrift.js test/units.js"
/home/travis/builds/simplereach/helenus/test/cql2.js
set_cql_version not supported, unsetting cqlVersion
whiskey.common: test.finish in [bold]test a bad connection will return an error[/bold] has been called twice, possible double callback in your code! {"name":"test a bad connection will return an error"}
  setUp                                                                      [OK]
  test a bad connection will return an error                                 [OK]
  test cql create keyspace                                                   [OK]
  test cql use keyspace                                                      [OK]
  test cql create column family                                              [OK]
  test cql create counter column family                                      [OK]
  test cql create reversed column family                                     [OK]
  test cql update                                                            [OK]
  test cql update reversed                                                   [OK]
  test cql update with no callback                                           [OK]
  test cql incr                                                              [OK]
  test cql select                                                            [OK]
  test cql select reversed                                                   [OK]
  test cql select *                                                          [OK]
  test cql select counter                                                    [OK]
  test cql incr and select                                                   [OK]
  test cql select with bad user input                                        [OK]
  test cql count                                                             [OK]
  test cql error                                                             [OK]
  test cql count with gzip                                                   [OK]
  test cql delete                                                            [OK]
  test cql drop column family                                                [OK]
  test cql drop keyspace                                                     [OK]
  test too many cql params                                                   [OK]
  test too few cql params                                                    [OK]
  tearDown                                                                   [OK]
  timeout                                                               [TIMEOUT]
/home/travis/builds/simplereach/helenus/test/cql3.js
set_cql_version not supported, skipping CQL3 tests
/home/travis/builds/simplereach/helenus/test/thriftHostPool.js
whiskey.common: test.finish in [bold]test bad pool connect[/bold] has been called twice, possible double callback in your code! {"name":"test bad pool connect"}
  setUp                                                                      [OK]
  test pool.connect without keyspace                                         [OK]
  test pool.close without keyspace                                           [OK]
  test pool.connect with keyspace                                            [OK]
  test bad pool connect                                                      [OK]
  test pool.createKeyspace                                                   [OK]
  test pool.use                                                              [OK]
  test keyspace.createColumnFamily                                           [OK]
  test keyspace.createColumnFamily with composite type                       [OK]
  test keyspace.createSuperColumnFamily                                      [OK]
  test keyspace.createCounterFamily                                          [OK]
  test keyspace.get                                                          [OK]
  test keyspace.get composite                                                [OK]
  test keyspace.get supercolumn                                              [OK]
  test keyspace.get counter                                                  [OK]
  test keyspace.get from cache                                               [OK]
  test keyspace.get from index                                               [OK]
  test keyspace.get invalid cf                                               [OK]
  test standard cf.insert                                                    [OK]
  test standard cf.insert with custom CL                                     [OK]
  test standard cf.insert into composite cf                                  [OK]
  test counter cf.incr                                                       [OK]
  test standard cf.get                                                       [OK]
  test standard cf.get for composite column family                           [OK]
  test standard cf.get with options                                          [OK]
  test standard cf.get with custom CL                                        [OK]
  test standard cf.get with columns names                                    [OK]
  test composite cf.get with columns names                                   [OK]
  test counter cf.get with columns names                                     [OK]
  test standard cf.get with error                                            [OK]
  test standard cf with Index                                                [OK]
  test standard cf with BytestType                                           [OK]
  test standard cf with LongType                                             [OK]
  test standard cf with IntegerType                                          [OK]
  test standard cf with UTF8Type                                             [OK]
  test standard cf with AsciiType                                            [OK]
  test standard cf with LexicalUUIDType                                      [OK]
  test standard cf with TimeUUIDType                                         [OK]
  test standard cf with FloatType                                            [OK]
  test standard cf with DoubleType                                           [OK]
  test standard cf with DateType                                             [OK]
  test standard cf with BooleanType                                          [OK]
  test standard cf with UUIDType                                             [OK]
  test row.nameSlice                                                         [OK]
  test row.slice                                                             [OK]
  test row.toString and row.inspect                                          [OK]
  test row.forEach                                                           [OK]
  test standard cf remove column                                             [OK]
  test composite cf remove column                                            [OK]
  test standard cf remove row                                                [OK]
  test standard cf truncate                                                  [OK]
  test keyspace.dropColumnFamily                                             [OK]
  test pool.dropKeyspace                                                     [OK]
  test pool.close                                                            [OK]
  tearDown                                                                   [OK]
  timeout                                                               [TIMEOUT]
/home/travis/builds/simplereach/helenus/test/thrift.js
whiskey.common: test.finish in [bold]test bad pool connect[/bold] has been called twice, possible double callback in your code! {"name":"test bad pool connect"}
  setUp                                                                      [OK]
  test pool.connect without keyspace                                         [OK]
  test pool.close without keyspace                                           [OK]
  test pool.connect with keyspace                                            [OK]
  test bad pool connect                                                      [OK]
  test pool.createKeyspace                                                   [OK]
  test pool.use                                                              [OK]
  test keyspace.createColumnFamily                                           [OK]
  test keyspace.createColumnFamily with composite type                       [OK]
  test keyspace.createSuperColumnFamily                                      [OK]
  test keyspace.createCounterFamily                                          [OK]
  test keyspace.get                                                          [OK]
  test keyspace.get composite                                                [OK]
  test keyspace.get supercolumn                                              [OK]
  test keyspace.get counter                                                  [OK]
  test keyspace.get from cache                                               [OK]
  test keyspace.get from index                                               [OK]
  test keyspace.get invalid cf                                               [OK]
  test standard cf.insert                                                    [OK]
  test standard cf.insert with custom CL                                     [OK]
  test standard cf.insert into composite cf                                  [OK]
  test counter cf.incr                                                       [OK]
  test standard cf.get                                                       [OK]
  test standard cf.get for composite column family                           [OK]
  test standard cf.get with options                                          [OK]
  test standard cf.get with custom CL                                        [OK]
  test standard cf.get with columns names                                    [OK]
  test composite cf.get with columns names                                   [OK]
  test counter cf.get with columns names                                     [OK]
  test standard cf.get with error                                            [OK]
  test standard cf with Index                                                [OK]
  test standard cf with BytestType                                           [OK]
  test standard cf with LongType                                             [OK]
  test standard cf with IntegerType                                          [OK]
  test standard cf with UTF8Type                                             [OK]
  test standard cf with AsciiType                                            [OK]
  test standard cf with LexicalUUIDType                                      [OK]
  test standard cf with TimeUUIDType                                         [OK]
  test standard cf with FloatType                                            [OK]
  test standard cf with DoubleType                                           [OK]
  test standard cf with DateType                                             [OK]
  test standard cf with BooleanType                                          [OK]
  test standard cf with UUIDType                                             [OK]
  test row.nameSlice                                                         [OK]
  test row.slice                                                             [OK]
  test row.toString and row.inspect                                          [OK]
  test row.forEach                                                           [OK]
  test standard cf remove column                                             [OK]
  test composite cf remove column                                            [OK]
  test standard cf remove row                                                [OK]
  test standard cf truncate                                                  [OK]
  test keyspace.dropColumnFamily                                             [OK]
  test pool.dropKeyspace                                                     [OK]
  test pool.close                                                            [OK]
  tearDown                                                                   [OK]
  timeout                                                               [TIMEOUT]
/home/travis/builds/simplereach/helenus/test/units.js
  setUp                                                                      [OK]
  test uuid library                                                          [OK]
---------------------------------------------------------------------------------
Ran 138 tests in 45.345s

Successes: 138
Failures: 0
Timeouts: 3
Skipped: 0

FAILED

Leaked Variables

  cql2.js: errno
  thriftHostPool.js: errno
  thrift.js: errno
  units.js: no leaks detected
make: *** [test] Error 3

Done. Build script exited with: 1
```

### PR DESCRIPTION
**Pull request by calvinfo**
Fixes #74 - the final callback should just return rather than continuing to monitor. Maybe just merged oddly.

### CODE REVIEW

**Comment by calvinfo** [comment]
I'm thinking that the pool should monitor connections even if it can't connect right away. I'm going to try a few things out.

**Comment by devdazed** [comment]
The expected behavior is that it should be ready once it has connected successfully to at least one node.  If it can't connect to any node then it throws an error.  If it drops a connection to a node, it should retry the connection until it reconnects or it can no longer connect to any node.

**Comment by devdazed** [comment]
did you mean to close this?

**Comment by calvinfo** [comment]
If that's the expected behavior - then the commits up there which returning the `replyNotAvailable` fix all the tests and timeouts.

The scenario I'm considering is that you try connecting to a host which is down. Even if it's down right away, I'd like to reconnect to it when it it becomes available again.

**Comment by devdazed** [comment]
What I want to keep away from, and what a lot of drivers currently do, is silently queue up all requests until it can connect then once it does connect it will run all of the requests. 

This sounds good in theory but in practice it can be disastrous.  If there is a decent load on the connection and the server doesn't come up right away, what actually happens is that Node will blow its heap, and the app will exit without a stack and fail, leaving the user confused as to what happened.

If there isn't a load on the server, it will queue up the requests until all the `wanted` threads are taken (default is 5 I think) at which point it will just block, leaving the user confused as to what is going on.  

So as long as the user has some sort of feedback as to the fact that there is an error (whether it is  emitted and caught on the emitter side, or returned as a callback error) I am happy with it, and we can continue to try to reconnect, letting the app decide whether it should fail on the error or not.

I still think an error event should be emitted so that if the user is not listening for it, it will get bubbled up to `uncaughtException`, downing the app. If they want to listen on it then it will not go to `uncaughtException` and they can decide what to do with it.  This will also ensure that if `close` is called on the server side, we will still emit the error even though the user may have not made any queries.

Does this all make sense?

**Comment by calvinfo** [comment]
Yeah, that definitely makes sense to me. I've been bitten by this in a few of the mongo drivers. It's also not to hard to build a layer on top of the client if you really want it too. The not-queuing requests seems like a good idea.

Ideally I'd like the callback to return an error that can't connect to any of the hosts (and even emit). As long as it informs the app of the error and lets it deal with it however you'd like. 

If it's unavailable, I'd like the client to keep trying to re-connect internally. I do agree that requests during that time should just return an error so the calling code knows how to deal with it.

**Pull request closed without merging**
