### PR TITLE
Adding Increment Operation

### PR DESCRIPTION
**Pull request by calvinfo**
Still pretty basic, and I'm happy to take feedback on it. It adds the increment operation to the helenus client for counter columns. 

Unfortunately, it doesn't work with small negative numbers because of the way the node thrift client works. I filed an issue here: https://github.com/simplereach/node-thrift/issues/1

### CODE REVIEW

**Comment by devdazed** [comment]
This looks great! I will merge it once I look a little deeper into the thrift issue with negative numbers.

**Comment by calvinfo** [comment]
Great, that would be awesome! My particular use case doesn't include negative increments, so I would be okay with it being merged before the other fix goes through. For completeness though the negatives are good to have. Thanks again!

**Comment by calvinfo** [comment]
I'm adding a commit, there's a bug with select \* CQL queries where the array skips the 'KEY' column, but i continues to increment. 

If the row array adds to the map based upon its current length, there is no problem with either sort of query, ones via thrift or via CQL.

An example of reproing this kind of thing, if you have rows with a column A.

``` javascript

pool.cql('select * from Test', [], function (err, rows) {

  var row = rows[0];
  row['A']; // out of array length since KEY is skipped, but array only has one element

});
```

**Comment by calvinfo** [comment]
Thanks for merging this in!

**Pull request closed without merging**
