### PR TITLE
Add support for thrift getRange

### PR DESCRIPTION
**Pull request by psanford**
This pull request builds on @calvinfo's work to add getRange. 
- Added tests
- Added option to limit number of rows returned
- Fixed thrift handling of falsey values for KeyRange

### CODE REVIEW

**Comment by calvinfo** [comment]
Sweet! Thanks for finishing it up! :D

The stream still needs a few extra methods which aren't implemented by the base stream class. I'd create a prototype similar to the [mongoose querystream](https://github.com/LearnBoost/mongoose/blob/master/lib/querystream.js) and then add methods so that the caller can decide to pause and resume the stream at will. All you need are the [readable stream methods, and you're good](http://nodejs.org/docs/v0.8.14/api/stream.html#stream_readable_stream). The bonus would be loading columns in a streaming interface too.

Also, it's worth noting that node 0.10 recently pushed a new streaming API which is not forwards compatible (0.8 can't use a 0.10 stream), but gives you a lot of cool features right out of the box. It's still pretty new, but it would be great to have for helenus going forward. I'd make the QueryStream an instance of `stream.Readable` put into objectMode, and push Rows onto the stream. Since it's still so new though, and old streams probably won't be phased out completely until 0.12, that can probably wait.

Awesome job - our startup had a pretty major shift and I had to take a break from working on helenus. Glad to have you help complete this feature :)

**Comment by devdazed** [comment]
there is an NPM package that allows for node 0.10 streams with 0.8

**Comment by calvinfo** [comment]
Yeah, @devdazed  is right. Basing off https://github.com/isaacs/readable-stream would probably be a good idea now that the API has stabilized a bit.

**Comment by psanford** [comment]
Totally agree with all the feedback. I'll look into adding the flow control stuff over the weekend and I'll target the radable-stream api.

**Pull request closed without merging**
