### PR TITLE
Basic CQL3 Support

### PR DESCRIPTION
**Pull request by chris-rock**
Fixed some issues. It is now possible to add cql3 querys for cassandra 1.2. results are parsed as binary at the moment. 

We need to discuss how the parsing should be done for lists, maps and sets. At the end, I would expect, that data is returned as inserted.

related #89

### CODE REVIEW

**Comment by devdazed** [comment]
Thanks!
Does this pass the tests?

**Comment by chris-rock** [comment]
it pass all the cql tests, but not yet the all thrift tests...

**Comment by devdazed** [comment]
what if we revert the changes you made to the thrift-gen code, will it pass then?  Right now, Cassandra doesnt support thrift > 0.7.  Also, we should never use the version "*" in the package.json, it should always be pinned to a stable version that works.

**Comment by chris-rock** [comment]
I reverted those already, because timestamps are not properly handled with node-thrift. I am not sure if the new cassandra.thrift from 1.2 leads to this behaviour. I haven't applied your patches, maybe that's the reason?

**Comment by devdazed** [comment]
we need to re-compile it with the thrift 0.7.0 compiler. Plus I don't like that the Thrift 0.9.0 compiles the variables a globally scoped, that is a very bad practice.

**Comment by chris-rock** [comment]
okay. got you. makes sense. I compiled cassandra-thrift also with a newer version. We need to recompile with 0.7.0.

**Comment by chris-rock** [comment]
replaced by #92

**Pull request closed without merging**
