### PR TITLE
Original code assumed that all string objects in the format of a UUID we...

### PR DESCRIPTION
**Pull request by azweb76**
We upgraded to the latest version and our code failed because we store an ID which looks like a UUID, but is text. Can you review the changes and if ok, please merge into master? Thanks, Dan

### CODE REVIEW

**Comment by devdazed** [comment]
I see where this can cause issue, however, the primary concern I have with this is that it may cause issues with those that aren't explicitly using the UUID type, rather using strings.  Anyone else want to chime in?

**Comment by azweb76** [comment]
Hi devdazed, thanks for responding so quickly. Can you think of another way to identify the value being passed in is a UUID? I know many DB providers use the data type of the value to determine the type of encoding or mapping to the underlying DB data type. Thanks

**Comment by azweb76** [comment]
Any word on this? We are currently passing in text that looks like a UUID, and the query is failing.

**Comment by asilvas** [comment]
@devdazed This "feature" is a bug imo. Auto-converting strings that happen to contain a UUID to a UUID is rather concerning as it is against our will. Keys can be anything, and I'd rather avoid having our data type changed from what we're storing it as. Effectively we're saying "this is our schema", but the helenus does "but we'll auto-convert these for you!".

**Comment by devdazed** [comment]
Sounds good to me. I'll bump & release.

**Comment by asilvas** [comment]
+1

**Pull request merged**
