### PR TITLE
feat: adds Date support to escapeCQL function

### PR DESCRIPTION
**Pull request by tim-dev**
Just allows for handling of the Date object.

### CODE REVIEW

**Comment by devdazed** [comment]
hey thanks! lets write some tests for it,  then I think it will be good to merge.

**Comment by tim-dev** [comment]
Cool, will do.  I'm thinking pre-1970 date, current date, and future date.  Should we worry about invalid dates or leave that to the developer?

**Comment by devdazed** [comment]
i think we should check for an invalid date, C\* may not like the response given by one

``` js
> d = new Date('asdfsg')
Invalid Date
> d instanceof Date
true
> d.getTime()
NaN
```

**Comment by tim-dev** [comment]
I can verify that C\* doesn't want a NaN.  I'll have it throw if getTime returns a NaN.

**Comment by tim-dev** [comment]
Ok, I think that'll do it.  Had to use an ISO date string rather than an integer because C\* < 2 complained about negative integers being invalid.

**Comment by devdazed** [comment]
Interesting, is there a reason why `toISOString()` didn't work?  also, from the looks of it, this will limit the resolution to the second rather than the millisecond?

**Comment by tim-dev** [comment]
After some more in-depth research, here are the major hurdles:
- C\* < 2.0.2 doesn't work with negative longs: https://issues.apache.org/jira/browse/CASSANDRA-6212
- C\* uses [parseDateStrictly](http://commons.apache.org/proper/commons-lang/javadocs/api-3.1/index.html) for ISO string parsing with [these patterns](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/serializers/TimestampSerializer.java), none of which include milliseconds.  

My [third commit](https://github.com/tim-dev/helenus/commit/ea4d28313f99ac86ab0dd71e36345381a28c0fec) had different logic for negative pre-epoch times, and tried to use `toISOString()`, but that failed with an `unable to coerce to a formatted date` error in all C\* versions due to the patterns mentioned above.

As the date string loses millisecond precision, I'm thinking it should use `getTime()` for all but the pre-epoch dates, which I assume no longer care about millisecond precision.  To get fully smart, it could examine the C\* version and only use the date format for earlier versions.  Do you happen to know off the top of your head how to check the C\* version here, or if that's even reasonable?

**Comment by tim-dev** [comment]
I commited a change that uses the long unless it's negative.  Let me know if that passes muster.

**Pull request merged**
