### PR TITLE
Cassandra long is now Bignum

### PR DESCRIPTION
**Pull request by duyleekun**
Some groundwork porting long `number` to `bignum` https://github.com/justmoon/node-bignum
Tests are passed by forcing it to use new bignum so this will break current API

### CODE REVIEW

**Comment by devdazed** [comment]
This is good work, however, I think we should give the user the option to use `bignum` or keep using Number. The default should be to keep using Number as we don't want to break backwards compatibility with people's applications.

**Comment by duyleekun** [comment]
I could wrap some `if then` in `ser` and `de` implementation but I can't think of any way for user to enable `bignum` mode
If it's per connection then it's way too complicated to implement :(
If it's a global state, I don't know how to do global state elegantly in node because node module is kind of new to me :(

**Comment by devdazed** [comment]
how about this.

remove node-bignum from the package.json.  If the user elects to install node-bignum then we use it, if they do not install node-bignum manually then it uses number.  

Then in the code just try to require node-bignum and if it fails just fall back to using number

**Comment by duyleekun** [comment]
This is fine by me but it will break apps that intentionally depend on node-bignum but doesn't want the bignum feature in helenus
IMO, there should be a more declarative way to do this.

**Comment by devdazed** [comment]
i agree with that, maybe in the connection/poll options?

**Comment by duyleekun** [comment]
It's gonna be a massive change in existing codebase and I'm not currently capable to do that :(
I'm still reading the source code and find out how everything is glued together but it may take a while.

**Pull request closed without merging**
