### PR TITLE
deserialize the key

### PR DESCRIPTION
**Pull request by wwwy3y3**
if I select the key in my query, the key should also be deserialized

### CODE REVIEW

**Comment by devdazed** [comment]
can we write a test for this and ensure that the existing tests still pass.

**Comment by wwwy3y3** [comment]
ok I'll do that soon

**Comment by wwwy3y3** [comment]
Hi, I write a uuid key deserializing test, you may take a look
also I fix a bug that if I set cqlVersion to '2.0.0', it will still execute cql3

**Comment by wwwy3y3** [comment]
@devdazed if there is anything wrong with code, just tell me, and I'll fix it
otherwise, I think it's good to merge
also, I think some pull requests should also be merged and update the version on NPM
Helenus is an important module in my project
thx!

**Pull request merged**
